### ISSUE TITLE
Bug while posting

### ISSUE THREAD

**Issue by Marinofull** [yaasita/edit-slack.vim#1]
When I try to save after write under the "=== Message ===" mark I get these two errors:

`Error detected while processing function edit_slack#WriteCh..<SNR>42_Post..<SNR>42_Exec_cmd:`

`E730: using List as a String`

add info:
I installed via bundle, and it's possible to access any chat and get updated messages.
vim 7.4

**Comment by Marinofull** [comment]
I also tried the binary edit-slack (linux 64) and compiled from the source (wich give me a different binary with 8MB). I've got the same error in both

**Comment by yaasita** [comment]
It does not occur in my environment.
Does it happen with the following settings?

```
# backup
cd ~
mkdir vim-backup
mv .vim .vimrc ~/vim-backup/

# Vundle install
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# vimrc
vim ~/.vimrc
    # set vimrc to the minimum setting
    # https://gist.github.com/yaasita/ce2123ea5425a3d4d9545ef2f431fcca
    # Please change the line of tokens
    :source %
    :PluginInstall

# download binary
cd .vim/bundle/edit-slack.vim/
curl -Lo edit-slack https://github.com/yaasita/edit-slack/releases/download/v0.2.0/linux-amd64-edit-slack
chmod +x edit-slack

# open slack channel
vim slack://ch
```

**Comment by iansheridan** [comment]
FYI

I upgraded `vim` to 8.* and everything worked.

😄
