### ISSUE TITLE
reload / notifications

### ISSUE THREAD

**Issue by robinfehr** [yaasita/edit-slack.vim#2]
without having a look at the code: 
an automatic reload would be nice to get some notifications within the tab where slack is opened.
is this maybe already configureable?

**Comment by yaasita** [comment]
Thank you for using.
Automatic reload may be possible using the CursorHoldI event.

```
au CursorHold * :e
```

There is a way to save the last line and discover the changes.
If a modified flag is attached, a plus mark is displayed on the tab.
```
set modified
```

![notifications](https://68.media.tumblr.com/98152b3253ff3944b3f49a0bbe199907/tumblr_on49fkkAp91riy4fno1_250.png)
