### ISSUE TITLE
dm do not work

### ISSUE THREAD

**Issue by zippeurfou** [yaasita/edit-slack.vim#3]
It does not show the `==Message==` and it tells me: 
![image](https://user-images.githubusercontent.com/4520383/40247805-9971f34e-5a9b-11e8-8171-9e362f95e219.png)
Note that I can manually do:
```
:set ma
```
Then insert:
```
=== Message ===
My message
``` 
and it works

**Comment by yamsergey** [comment]
Same for me. The problem is in `autoload/edit_slack.vim` at `if match(l:url,'\v^slack://../[a-zA-Z0-9\-_]+$') > -1`. In my case, the regexp didn't cover channel names with `.`. I've added the dot to the regexp and it starts works. Should I open PR?

**Comment by yaasita** [comment]
added dots to the channel regular expression.
please try with the current version.
