### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by malaniz** [yaasita/edit-slack.vim#4]
Are you planning support threads like a special file? that would be really great!
Awesome work!

**Comment by malaniz** [comment]
There are actually a lot of solutions for terminal using libpurple and so on ... but no one supports threads and this one is just awesome! I would love to help you implementing threads like another type of files.

**Comment by sunnypp** [comment]
I am also looking for a solution for threads and this library is awesome needless to say...
I have a look at the binary's source code: https://github.com/yaasita/edit-slack

With reference to [post.go](https://github.com/yaasita/edit-slack/blob/master/slack/post.go) and Slack documentation (https://api.slack.com/methods/chat.postMessage) I think replying to threads should be possible. (Ah but I don't have the time to fork and implement it yet...)

**Comment by yaasita** [comment]
I'm sorry to reply late.
I have implemented the thread feature.
https://github.com/yaasita/edit-slack.vim/commit/4d5ab7b24ef1033e864456367e977d5e73fd6976
